### ISSUE TITLE
Feedback squadpage

### ISSUE THREAD

**Issue by Patrickkhr** [lisavanmansom/connect-your-tribe-squad-page#1]
Wat is mooi, wat werkt goed?

Orgineel ontwerp en mooie afbeeldingen gebruikt op de website. 
Goed bijpassende lettertype en duidelijke hiërarchie op de pagina.

Wat kan beter, wat werkt niet zo goed?

De achtergrond afbeelding iets donkerder of onduidelijker maken zodat de tekst beter zichtbaar is.

**Comment by lisavanmansom** [comment]
Yes dankjewel! Ik heb de afbeelding donkerder gemaakt en nu is de tekst beter leesbaar.
