### ISSUE TITLE
Ontwerp analyseren

### ISSUE THREAD

**Issue by Abeeryu** [lisavanmansom/connect-your-tribe-squad-page#2]
Wat is mooi, Wat werkt goed?

Het idee van jouw squad pagina is prachtig. Ik vind het leuk dat je soort museum heb gemaakt.
Ik heb ook gemerkt dat de soorteren als form heb gemaakt en daarna in een leuke manier heb verwerkt in jouw pagina.
Mooie foto's en mooi idee!

Wat kan beter, Wat werkt niet goed?
Ik vind een goed manier om een buttons dat duidelijk zeggen "filter" en "soorteer", dat is wel dudelijk voor de eindgebruiker.

**Comment by lisavanmansom** [comment]
Yes dankjewel! er staat nu een button met filter

<img width="155" alt="Scherm­afbeelding 2024-02-26 om 12 31 21" src="https://github.com/lisavanmansom/connect-your-tribe-squad-page/assets/144007419/ae297720-9b4d-4499-b725-d75072d68a0c">
