### ISSUE TITLE
Analyse Ontwerp

### ISSUE THREAD

**Issue by Jason2426** [lisavanmansom/connect-your-tribe-squad-page#3]
**Wat is mooi?**
Het ontwerp is erg vet bedacht, super creatief en ziet er professioneel uit.  

**Wat werkt goed?**
De layout ziet er goed uit en werkt goed. Het is ook goed uitgedacht met bijvoorbeeld de foto's van de squadleden. Textvormgeving werkt goed en is erg leesbaar op bijna alle vlakken behalve op de kaartjes met de studenten zelf. 

**Wat werkt niet zo goed**
De filters zijn misschien nog niet helemaal uitgedacht maar er is wel al een ontwerp. De informatie en teksten op de kaartjes zelf kunnen nog wat beter weergeven worden maar voor de rest is het allemaal goed.

**Wat kan beter?**
Textvormgeving op een puntje na en heel misschien spelen met meer kleuren, het ziet er nu minimalistisch en chique uit maar misschien kan er nog wat kleur bij. Eventueel wat leuke animaties toevoegen voor de gebruikers interactie.

**Comment by lisavanmansom** [comment]
Yes dankjewel! Ik heb een animatie toegevoegd en kleur, ook zijn is de filter werkend
 
<img height="150" alt="Scherm­afbeelding 2024-02-26 om 12 28 54" src="https://github.com/lisavanmansom/connect-your-tribe-squad-page/assets/144007419/8a64bd6b-7b22-458c-ba19-aa8a886ab70d">
<img height="150" alt="Scherm­afbeelding 2024-02-26 om 12 28 25" src="https://github.com/lisavanmansom/connect-your-tribe-squad-page/assets/144007419/5d892f28-3e28-430b-87a2-70aed06bb120">
